import numpy as np
import matplotlib.pyplot as plt
import os

# Configuration: Map labels to the .npy files generated by your runners
DATASETS = {
    'SA Baseline (Slow Cooling)': '../out/sa_all_histories.npy',
    'GA Baseline (Standard)': '../out/ga_all_histories.npy',
    'GA V1 (Gentle Selection)': '../out/ga_v1_all_histories.npy',
    'GA V2 (High Diversity)': '../out/ga_v2_all_histories.npy',
    'GA V3 (Chaos Theory)': '../out/ga_v3_all_histories.npy'
}

def load_and_plot():
    plt.figure(figsize=(14, 8), dpi=150)
    
    for label, path in DATASETS.items():
        if not os.path.exists(path):
            print(f"Skipping {label}: File {path} not found yet.")
            continue
            
        # data shape is (30 runs, evaluations)
        data = np.load(path)
        num_runs = data.shape[0]
        num_steps = data.shape[1]
        
        # Aligning the X-axis to "Total Fitness Evaluations"
        # GA baseline/variants: 1000 generations * 500 pop = 500,000 evals
        # SA: 500,000 iterations = 500,000 evals
        if 'GA' in label:
            # Scale generations to total evaluations
            x_axis = np.linspace(0, 500000, num_steps)
        else:
            # SA iterations are already 1:1 with evaluations
            x_axis = np.arange(num_steps)

        # Statistical analysis across the 30 runs
        mean_fitness = np.mean(data, axis=0)
        std_fitness = np.std(data, axis=0)

        # Plot the mean line
        line, = plt.plot(x_axis, mean_fitness, label=f"{label} (Mean)", linewidth=2)
        
        # Plot shaded area representing the Standard Deviation (Reliability)
        plt.fill_between(x_axis, 
                         mean_fitness - std_fitness, 
                         mean_fitness + std_fitness, 
                         color=line.get_color(), 
                         alpha=0.15)
        
        print(f"Processed {label}: Peak Mean = {np.max(mean_fitness):.2f}")

    # Formatting the scientific plot
    plt.title("Effect of Selection and Diversity Parameters on Weighted $uv$ Coverage", fontsize=16)
    plt.xlabel("Total Fitness Evaluations", fontsize=12)
    plt.ylabel("Weighted $uv$ Coverage Score (Fitness)", fontsize=12)
    plt.legend(loc='lower right', frameon=True, shadow=True)
    plt.grid(True, linestyle='--', alpha=0.6)
    
    # Adding a vertical line at the GA "Plateau Point" for discussion
    plt.axvline(x=150000, color='gray', linestyle=':', alpha=0.5, label='Early GA Plateau')

    plt.tight_layout()
    output_path = "../out/final_comparison_all_variants.png"
    plt.savefig(output_path)
    print(f"\nMaster plot saved to: {output_path}")
    plt.show()

if __name__ == "__main__":
    load_and_plot()